#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false
write_files:
    - path: "/etc/environment"
      content: |-
         ANSIBLE_CMD="ansible-playbook -i environments/local -e docker_image_prefix=testing"
         TZ=Europe/London
runcmd:
 - > 
   export TZ=Europe/London ;
   echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections ;
   ln -snf /usr/share/zoneinfo/$TZ /etc/localtime ;
   echo $TZ > /etc/timezone
 - >
    apt-get update && apt-get -y upgrade &&
    apt-get -y install 
    build-essential
    software-properties-common apt-utils 
    lsb-release ca-certificates 
    curl wget gpg sudo 
    socat telnet inetutils-ping 
    unzip vim telnet less sudo git jq 
    python2 python2-dev libffi-dev libssl-dev
    python3-pip gcc g++ make 
    silversearcher-ag
 - >
    wget -O- https://apt.corretto.aws/corretto.key | apt-key add - ;
    add-apt-repository 'deb https://apt.corretto.aws stable main' ;
    apt-get update && apt-get -y install java-11-amazon-corretto-jdk ;
    pip3 install --upgrade pip setuptools six
 - >
    ln -sf /usr/bin/python2 /usr/bin/python ;
    curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py ;
    python get-pip.py ;
    python -m pip install ansible==2.8.18 pydocumentdb humanize requests
 - >
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list ;
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor > /usr/share/keyrings/docker-archive-keyring.gpg ;
    apt-get update && apt-get -y install docker-ce-cli docker-ce ;
    usermod -aG docker ubuntu
 - >
    curl -sL https://deb.nodesource.com/setup_16.x | bash ;
    apt-get install -y nodejs ;
    curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null ;
    echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list ;
    apt-get update && sudo apt-get install yarn
 - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
 - >
   curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-$(dpkg --print-architecture) ;
   chmod +x ./kind ; mv ./kind /usr/local/bin/kind
